services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: personaldb
      DB_USER: root
      DB_PASSWORD: mysql123
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy  # Wait for MySQL to be healthy

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: personaldb
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql123
      MYSQL_ROOT_PASSWORD: mysql123
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
