services:
  mysql:
    image: mysql:8.4
    container_name: 'database'
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: personaldb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  data-service:
    build:
      context: ./data-service
    container_name: 'data-service'
    environment:
      DB_HOST: mysql
      DB_PORT: 3307
      DB_NAME: personaldb
      DB_USER: root
      DB_PASSWORD: mysql123
      DB_ROOT_PASSWORD: mysql123
    ports: 
      - 8000:8000
    depends_on:
      mysql:
        condition: service_healthy
  auth-service:
    build:
      context: ./auth-service
    container_name: 'auth-service'
    ports: 
      - 8088:8088
    depends_on:
      mysql:
        condition: service_healthy
  app-service:
    build:
      context: ./app-service
    container_name: 'app-service'
    ports: 
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
      driver: local
