version: '3.8'  # Specify the version of Docker Compose

services:
  mysql:
    image: mysql:8.4
    container_name: 'database'
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: personaldb
    ports:
      - "3307:3306"  # Host port to container port mapping
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  data-service:
    build:
      context: ./data-service
    container_name: 'data-service'
    environment:
      DB_HOST: mysql  # This should be the service name
      DB_PORT: 3306  # Use the internal MySQL port
      DB_NAME: personaldb
      DB_USER: root
      DB_PASSWORD: mysql123
    ports: 
      - 8000:8000
    depends_on:
      mysql:
        condition: service_healthy

  auth-service:
    build:
      context: ./auth-service
    container_name: 'auth-service'
    ports: 
      - 8088:8088
    depends_on:
      mysql:
        condition: service_healthy

  app-service:
    build:
      context: ./app-service
    container_name: 'app-service'
    ports: 
      - 8080:8080
    volumes: 
      - .:/app-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:8088  # Use the service name here
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
      driver: local
